name: Sh Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: execute
        uses: luizm/action-sh-checker@v0.1.8

